force-app/main/default/objects/Pokedex_Entry__c/Pokedex_Entry__c.object-meta.xml
<CustomObject>
    <label>Pokedex Entry</label>
    <nameField>
        <label>Pokedex Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokedex Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokedex_Entry__c/fields/Trigger_API_Enrichment__c.field-meta.xml
<CustomField>
    <fullName>Trigger_API_Enrichment__c</fullName>
    <label>Trigger API Enrichment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TriggerHandlers/pokedexEntryTriggerHandler.cls
public class pokedexEntryTriggerHandler extends TriggerHandler {
    
    public override void handleAfterUpdate(){
        enrichPokedexEntryInfo();
    }

    public void enrichPokedexEntryInfo(){
        for(Pokedex_Entry__c pkdxEntry : (List<Pokedex_Entry__c>) this.newList){
            Pokedex_Entry__c oldPkdxEntry = (Pokedex_Entry__c) this.oldMap.get(pkdxEntry.Id);
           
            if(pkdxEntry.Trigger_API_Enrichment__c != oldPkdxEntry.Trigger_API_Enrichment__c){
                System.debug('API Call Triggered');
                pokeAPICallout.makeCallout(pkdxEntry.Name);

            }
        }
    }
}