force-app/main/default/objects/Battle__c/Battle__c.object-meta.xml
<CustomObject>
    <label>Battle</label>
    <nameField>
        <displayFormat>Battle-{0000}</displayFormat>
        <label>Battle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Battles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Battle__c/fields/Pokemon_1__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pokemon 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pokemon__c.Current_HP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Battles</relationshipLabel>
    <relationshipName>Battles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Battle__c/fields/Pokemon_2__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pokemon 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pokemon__c.Current_HP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Battles (Pokemon 2)</relationshipLabel>
    <relationshipName>Battles1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Move__c/Move__c.object-meta.xml
<CustomObject>
    <label>Move</label>
    <nameField>
        <displayFormat>MV-{0000}</displayFormat>
        <label>Move Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Moves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Move__c/fields/Max_PP__c.field-meta.xml
<CustomField>
    <fullName>Max_PP__c</fullName>
    <label>Max PP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/Move__c.field-meta.xml
<CustomField>
    <fullName>Move__c</fullName>
    <formula>TM__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Move</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Moves</relationshipLabel>
    <relationshipName>Moves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>TM</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Moves</relationshipLabel>
    <relationshipName>Moves</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(TM__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <displayFormat>PKMN-{0000}</displayFormat>
        <label>Pokemon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>TM</label>
    <nameField>
        <label>TM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TM__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
            <value>
                <fullName>Status Modifier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TM__c/fields/Power__c.field-meta.xml
<CustomField>
    <fullName>Power__c</fullName>
    <label>Power</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TM__c/fields/PP__c.field-meta.xml
<CustomField>
    <fullName>PP__c</fullName>
    <label>PP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TM__c/fields/Status_Modifier__c.field-meta.xml
<CustomField>
    <fullName>Status_Modifier__c</fullName>
    <label>Status Modifier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Modifiers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status_Modifiers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Paralyzed</fullName>
    </customValue>
    <customValue>
        <fullName>Burn</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Confused</fullName>
    </customValue>
    <masterLabel>Status Modifiers</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Controllers/battleWindowController.cls
public class battleWindowController {
    
    @AuraEnabled
    public static List<Object> pkmnMoves(String BattleId, Integer Pkmn){

        if(Pkmn == 1){
            Battle__c battle = [SELECT Id, Pokemon_1__c FROM Battle__c WHERE Id = :BattleId LIMIT 1];
            System.debug('Battle Id: ' + battle);
            System.debug('Pkmn 1 Id: ' + battle.Pokemon_1__c);

            List<Object> moveList = [
                SELECT Id, Pokemon__c, Move__c, Type__c, PP__c, Max_PP__c,
                TM__r.Category__c, TM__r.Power__c, TM__r.Type__c,
                TM__r.Name,TM__r.Status_Modifier__c
                FROM Move__c 
                WHERE Pokemon__c = :battle.Pokemon_1__c LIMIT 4
                ];
            system.debug(moveList);
            return moveList;
        } else {
            Battle__c battle = [SELECT Id, Pokemon_2__c FROM Battle__c WHERE Id = :BattleId LIMIT 1];
            System.debug('Battle Id: ' + battle);
            System.debug('Pkmn 2 Id: ' + battle.Pokemon_2__c);

            List<Object> moveList = [
                SELECT Id, Pokemon__c, Move__c, Type__c, PP__c, Max_PP__c,
                TM__r.Category__c, TM__r.Power__c, TM__r.Type__c,
                TM__r.Name,TM__r.Status_Modifier__c
                FROM Move__c 
                WHERE Pokemon__c = :battle.Pokemon_2__c LIMIT 4
                ];
            system.debug(moveList);
            return moveList;  
        }

        
        
    }

}