force-app/main/default/objects/Battle__c/Battle__c.object-meta.xml
<CustomObject>
    <label>Battle</label>
    <nameField>
        <displayFormat>Battle-{0000}</displayFormat>
        <label>Battle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Battles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Battle__c/fields/Pokemon_1__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pokemon 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pokemon__c.Current_HP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Battles</relationshipLabel>
    <relationshipName>Battles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Battle__c/fields/Pokemon_2__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pokemon 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pokemon__c.Current_HP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Battles (Pokemon 2)</relationshipLabel>
    <relationshipName>Battles1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Move__c/Move__c.object-meta.xml
<CustomObject>
    <label>Move</label>
    <nameField>
        <displayFormat>MV-{0000}</displayFormat>
        <label>Move Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Moves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Move__c/fields/Move__c.field-meta.xml
<CustomField>
    <fullName>Move__c</fullName>
    <formula>TM__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Move</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Moves</relationshipLabel>
    <relationshipName>Moves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>TM</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Moves</relationshipLabel>
    <relationshipName>Moves</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pokedex_Entry__c/Pokedex_Entry__c.object-meta.xml
<CustomObject>
    <label>Pokedex Entry</label>
    <nameField>
        <label>Pokedex Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokedex Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokedex_Entry__c/fields/Sprite_Back_URL__c.field-meta.xml
<CustomField>
    <fullName>Sprite_Back_URL__c</fullName>
    <label>Sprite Back URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Pokedex_Entry__c/fields/Sprite_Front_URL__c.field-meta.xml
<CustomField>
    <fullName>Sprite_Front_URL__c</fullName>
    <label>Sprite Front URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <displayFormat>PKMN-{0000}</displayFormat>
        <label>Pokemon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Pokedex_Entry__c.field-meta.xml
<CustomField>
    <fullName>Pokedex_Entry__c</fullName>
    <label>Pokedex Entry</label>
    <referenceTo>Pokedex_Entry__c</referenceTo>
    <relationshipLabel>Pokemon</relationshipLabel>
    <relationshipName>Pokemon</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Sprite_Back_URL__c.field-meta.xml
<CustomField>
    <fullName>Sprite_Back_URL__c</fullName>
    <formula>Pokedex_Entry__r.Sprite_Back_URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sprite Back URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Sprite_Front_URL__c.field-meta.xml
<CustomField>
    <fullName>Sprite_Front_URL__c</fullName>
    <formula>Pokedex_Entry__r.Sprite_Front_URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sprite Front URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>TM</label>
    <nameField>
        <label>TM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TM__c/fields/Move_Id__c.field-meta.xml
<CustomField>
    <fullName>Move_Id__c</fullName>
    <externalId>true</externalId>
    <label>Move Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TM__c/fields/Power__c.field-meta.xml
<CustomField>
    <fullName>Power__c</fullName>
    <label>Power</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Controllers/battleWindowControllerTest.cls
@isTest
private class battleWindowControllerTest {
    
    @TestSetup
    static void setup(){
        
        List<Pokedex_Entry__c> pkdxEntries = new List<Pokedex_Entry__c>();
        List<Pokemon__c> pkmns = new List<Pokemon__c>();
        List<Move__c> moves = new List<Move__c>();
        
        List<TM__c> tms = new List<TM__c>();
        Integer numTmsToCreate = 4;

        //insert TMs
        for(Integer i = 0; i < numTmsToCreate; i++){
            TM__c tm = new TM__c();
            tm.Name = 'Test TM '+ (i+1);
            tm.Power__c = 100;
            tm.Move_Id__c = (i+1); 
            tms.add(tm);
        }
        insert tms;
        
        //insert pokedex entries
        for(Integer i=0;i<2;i++){
            Pokedex_Entry__c pkdxEntry = new Pokedex_Entry__c();
            pkdxEntry.Name = 'Test Poke ' + (i+1);
            pkdxEntry.Sprite_Back_URL__c = 'testBack' + (i+1);
            pkdxEntry.Sprite_Front_URL__c = 'testFront' + (i+1);

            pkdxEntries.add(pkdxEntry);
        }
        insert pkdxEntries;

        //insert pokemon
        for(Pokedex_Entry__c entry : pkdxEntries){
            Pokemon__c pkmn = new Pokemon__c();
            pkmn.Pokedex_Entry__c = entry.Id;

            pkmns.add(pkmn);
        }
        insert pkmns;


        //insert moves
        for(Integer i=0; i<tms.size(); i++){
            Move__c pkmn1Mv = new Move__c();
            pkmn1Mv.TM__c = tms[i].id;
            pkmn1Mv.Pokemon__c = pkmns[0].id;

            Move__c pkmn2Mv = new Move__c();
            pkmn2Mv.TM__c = tms[i].id;
            pkmn2Mv.Pokemon__c = pkmns[1].id;

            moves.add(pkmn1Mv, pkmn2Mv);
        }
        insert moves;

        Battle__c battle = new Battle__c();
        battle.Pokemon_1__c = pkmns[0].Id;
        battle.Pokemon_2__c = pkmns[1].Id;
        insert battle;
    }

    @isTest
    static void testLeftImgUrl(){
        Battle__c battle = [SELECT Id FROM Battle__c LIMIT 1];

        String url = battleWindowController.leftPkmnImgUrl(battle.Id);

        Assert.isNotNull(url, 'URL should not be null');
    }

    @isTest
    static void testRightImgUrl(){
        Battle__c battle = [SELECT Id FROM Battle__c LIMIT 1];

        String url = battleWindowController.rightPkmnImgUrl(battle.Id);

        Assert.isNotNull(url, 'URL should not be null');
    }
}