force-app/main/default/objects/Battle__c/Battle__c.object-meta.xml
<CustomObject>
    <label>Battle</label>
    <nameField>
        <displayFormat>Battle-{0000}</displayFormat>
        <label>Battle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Battles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Battle__c/fields/Pokemon_1__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pokemon 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pokemon__c.Current_HP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Battles</relationshipLabel>
    <relationshipName>Battles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Battle__c/fields/Pokemon_2__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pokemon 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pokemon__c.Current_HP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Battles (Pokemon 2)</relationshipLabel>
    <relationshipName>Battles1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Battle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pokedex_Entry__c/Pokedex_Entry__c.object-meta.xml
<CustomObject>
    <label>Pokedex Entry</label>
    <nameField>
        <label>Pokedex Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokedex Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <displayFormat>PKMN-{0000}</displayFormat>
        <label>Pokemon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Current_HP__c.field-meta.xml
<CustomField>
    <fullName>Current_HP__c</fullName>
    <label>Current HP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Max_HP__c.field-meta.xml
<CustomField>
    <fullName>Max_HP__c</fullName>
    <label>Max HP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Pokedex_Entry__c.field-meta.xml
<CustomField>
    <fullName>Pokedex_Entry__c</fullName>
    <label>Pokedex Entry</label>
    <referenceTo>Pokedex_Entry__c</referenceTo>
    <relationshipLabel>Pokemon</relationshipLabel>
    <relationshipName>Pokemon</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Modifiers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status_Modifiers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Paralyzed</fullName>
    </customValue>
    <customValue>
        <fullName>Burn</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Confused</fullName>
    </customValue>
    <masterLabel>Status Modifiers</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerHandlers/PokemonTriggerHandler.cls
public class PokemonTriggerHandler {
    
    //Before
    public static void beforeInsert(List<Pokemon__c> newPokemon, Map<Id, SObject> newAccountMap){
        System.debug('Handler - Before Insert Triggered');
        
        Set<Id> pkdxEntryIds = new Set<Id>();
        
        for(Pokemon__c pkmn : newPokemon){
            if(pkmn.Pokedex_Entry__c != null){
                pkdxEntryIds.add(pkmn.Pokedex_Entry__c);
            }
        }

        Map<Id, Pokedex_Entry__c> pkdxEntries = new Map<Id, Pokedex_Entry__c>([SELECT Id, HP__c FROM Pokedex_Entry__c WHERE Id IN :pkdxEntryIds]);

        for(Pokemon__c pkmn : newPokemon){
            pkmn.Max_HP__c = pkdxEntries.get(pkmn.Pokedex_Entry__c).HP__c;
            pkmn.Current_HP__c = pkdxEntries.get(pkmn.Pokedex_Entry__c).HP__c;
        }
    }
    
    public static void beforeUpdate(List<Pokemon__c> newPokemon, List<Pokemon__c> oldPokemon, Map<Id, Pokemon__c> oldPokemonMap, Map<Id, Pokemon__c> newPokemonMap){
        System.debug('Handler - Before Update Triggered');

        //if current HP is < 0, current HP is 0
        for(Pokemon__c pkmn : newPokemon){
            if(pkmn.Current_HP__c < 0){
                pkmn.Current_HP__c = 0;
            }

            if(pkmn.Current_HP__c <= 0 && pkmn.Status__c != null){
                pkmn.Status__c = null;
            }
        }
    }

    //After
    public static void afterInsert(List<Pokemon__c> newPokemon, List<Pokemon__c> oldPokemon, Map<Id, Pokemon__c> oldPokemonMap, Map<Id, Pokemon__c> newPokemonMap){
        System.debug('Handler - After Insert Triggered');
    }

    public static void afterUpdate(List<Pokemon__c> newPokemon, List<Pokemon__c> oldPokemon, Map<Id, Pokemon__c> oldPokemonMap, Map<Id, Pokemon__c> newPokemonMap){
        System.debug('Handler - After Update Triggered');

        //Close battles when pokemon faints
        for(Pokemon__c pkmn : newPokemon){
            Pokemon__c oldPkmn = oldPokemonMap.get(pkmn.Id);
            if(pkmn.Current_HP__c == 0 && oldPkmn.Current_HP__c != 0){
                
                //SOQL QUERY IN A FOR LOOP REEEEEEEEEE
                List<Battle__c> battles = [
                    SELECT Id 
                    FROM Battle__c 
                    WHERE Pokemon_1__c = :pkmn.Id 
                    OR Pokemon_2__c = :pkmn.Id
                    ];  
                System.debug('Found Battles: ' + battles.size());
                
                List<Battle__c> battlesToUpdate = new List<Battle__c>();
                for(Battle__c battle : battles){
                    battle.Status__c = 'Completed';
                    battlesToUpdate.add(battle);
                }

                update battlesToUpdate;

            }
        }
    }

}