force-app/main/default/objects/Battle__c/Battle__c.object-meta.xml
<CustomObject>
    <label>Battle</label>
    <nameField>
        <displayFormat>Battle-{0000}</displayFormat>
        <label>Battle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Battles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Battle__c/fields/Pokemon_1__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pokemon 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pokemon__c.Current_HP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Battles</relationshipLabel>
    <relationshipName>Battles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Battle__c/fields/Pokemon_2__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pokemon 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Pokemon__c.Current_HP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Battles (Pokemon 2)</relationshipLabel>
    <relationshipName>Battles1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Battle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Battle__c/fields/Victor__c.field-meta.xml
<CustomField>
    <fullName>Victor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Victor</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Battles (Victor)</relationshipLabel>
    <relationshipName>Battles2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <displayFormat>PKMN-{0000}</displayFormat>
        <label>Pokemon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Current_HP__c.field-meta.xml
<CustomField>
    <fullName>Current_HP__c</fullName>
    <label>Current HP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Modifiers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status_Modifiers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Paralyzed</fullName>
    </customValue>
    <customValue>
        <fullName>Burn</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Confused</fullName>
    </customValue>
    <masterLabel>Status Modifiers</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerHandlers/battleTriggerHandler.cls
public class battleTriggerHandler {
    
    public static void beforeInsert(List<Battle__c> newBattle, Map<Id, Battle__c> newBattleMap){

    }

    public static void beforeUpdate(List<Battle__c> newBattle, List<Battle__c> oldBattle, Map<Id, Battle__c> newBattleMap, Map<Id, Battle__c> oldBattleMap){
        
        //SOQL Query to get a map of all Pokemon that are either pokemon 1 or pokemon 2
        // Map<Id, Pokemon__c> relatedPkmn = new Map<Id, Pokemon__c>([
        //     SELECT Id, Name 
        //     FROM Pokemon__c 
        //     WHERE (Id IN :newBattle.Pokemon_1__c OR Id IN :newBattle.Pokemon_2__c)
        //     ]);
        

        for(Battle__c newBattleRec : newBattle){
            Battle__c oldBattleRec = oldBattleMap.get(newBattleRec.Id); 
            if(newBattleRec.Status__c != oldBattleRec.Status__c){
                //mark victor
                if(newBattleRec.Pokemon_1__r.Current_HP__c > newBattleRec.Pokemon_2__r.Current_HP__c){
                    newBattleRec.Victor__c = newBattleRec.Pokemon_1__c;
                } else {
                    newBattleRec.Victor__c = newBattleRec.Pokemon_2__c;
                }
            }
        }

    }

    public static void afterInsert(List<Battle__c> newBattle, Map<Id, Battle__c> newBattleMap){

    }

    public static void afterUpdate(List<Battle__c> newBattle, List<Battle__c> oldBattle, Map<Id, Battle__c> newBattleMap, Map<Id, Battle__c> oldBattleMap){

    }
}