force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <displayFormat>PKMN-{0000}</displayFormat>
        <label>Pokemon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Pokemon_Name__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_Name__c</fullName>
    <formula>Pokedex_Entry__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pokemon Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>TM</label>
    <nameField>
        <label>TM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TM__c/fields/Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Accuracy__c</fullName>
    <label>Accuracy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TM__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
            <value>
                <fullName>Status Modifier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TM__c/fields/Move_Id__c.field-meta.xml
<CustomField>
    <fullName>Move_Id__c</fullName>
    <externalId>true</externalId>
    <label>Move Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TM__c/fields/Power__c.field-meta.xml
<CustomField>
    <fullName>Power__c</fullName>
    <label>Power</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TM__c/fields/PP__c.field-meta.xml
<CustomField>
    <fullName>PP__c</fullName>
    <label>PP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/APICallouts/pokeAPIMoveService.cls
public without sharing class pokeAPIMoveService {
    
    @AuraEnabled(cacheable=true)
    public static List<TM__c> makeCallout(String pokemonId){
        
        //queries for the pkmns name since we dont have it in the LWC
        String pokemonName = [SELECT Pokemon_Name__c FROM Pokemon__c WHERE Id = :pokemonId].Pokemon_Name__c;
        System.debug('Pokemon Name: ' + pokemonName);

        //sets up endpoint URL
        String endpointURL = 'https://pokeapi.co/api/v2/pokemon/'+ pokemonName.toLowerCase();
        System.debug('Endpoint URL: '+ endpointURL);

        //instantiates Http callout
        Http http = new Http();
        HttpRequest req = new HttpRequest();

        req.setEndpoint(endpointURL);
        req.setMethod('GET');

        //sends request
        HttpResponse response = http.send(req);

        pokemonMove wrapperClass = new pokemonMove();

        if(response.getStatusCode() == 200){
            System.debug('==== CALLOUT SUCCESSFULL ====');
            Map<String, Object> pokemonData = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            
            
            wrapperClass = (pokemonMove) json.deserialize(response.getBody(), pokemonMove.class);
            System.debug('Wrapper Class Data: ' + wrapperClass);

        }
        
        return retrieveMoves(wrapperClass.Moves);
    }

    private static List<TM__c> retrieveMoves(List<pokemonMove.MoveData> wcMoves){
        List<Integer> moveIds = new List<Integer>();
        
        for(pokemonMove.MoveData move: wcMoves){
            String moveId = move.move.url;
            moveId = moveId.remove('https://pokeapi.co/api/v2/move/');
            moveId = moveId.remove('/');
            moveIds.add(Integer.valueOf(moveId));
            System.debug('Move Id: ' + moveId);
        } 

        

        List<TM__c> TMList = [
            SELECT Id, Name, Type__c, Power__c, Accuracy__c, Category__c, PP__c 
            FROM TM__c 
            WHERE Move_Id__c 
            IN :moveIds
            ];

        System.debug('TMs: ' + TMList);
        

        return TMList;

    }
}