force-app/main/default/objects/Move__c/Move__c.object-meta.xml
<CustomObject>
    <label>Move</label>
    <nameField>
        <displayFormat>MV-{0000}</displayFormat>
        <label>Move Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Moves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Move__c/fields/Max_PP__c.field-meta.xml
<CustomField>
    <fullName>Max_PP__c</fullName>
    <label>Max PP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/Move__c.field-meta.xml
<CustomField>
    <fullName>Move__c</fullName>
    <formula>TM__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Move</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>TM</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Moves</relationshipLabel>
    <relationshipName>Moves</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>TM</label>
    <nameField>
        <label>TM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TM__c/fields/PP__c.field-meta.xml
<CustomField>
    <fullName>PP__c</fullName>
    <label>PP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggerHandlers/MoveTriggerHandler.cls
public class MoveTriggerHandler extends TriggerHandler {
    
    public override void handleBeforeInsert(){
        setDefaultPP();
    }

    public void setDefaultPP(){
        Set<Id> tmIds = new Set<Id>();
        
        for(Move__c move : (List<Move__c>) this.newList){
            tmIds.add(move.TM__c);
        }

        Map<Id, TM__c> tmMap = new Map<Id, TM__c>();
        if(!tmIds.isEmpty()){
            tmMap = new Map<Id, TM__c>([
                SELECT Id, PP__c
                FROM TM__c
                WHERE ID in :tmIds
            ]);
        }

        for(Move__c move : (List<Move__c>) this.newList){
            if(move.PP__c == null && move.TM__c != null){
                move.PP__c = tmMap.get(move.TM__c).PP__c;
                move.Max_PP__c = tmMap.get(move.TM__c).PP__c;
            }
        }
    }
    
    
}