force-app/main/default/objects/Move__c/Move__c.object-meta.xml
<CustomObject>
    <label>Move</label>
    <nameField>
        <displayFormat>MV-{0000}</displayFormat>
        <label>Move Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Moves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Move__c/fields/Max_PP__c.field-meta.xml
<CustomField>
    <fullName>Max_PP__c</fullName>
    <label>Max PP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/Move__c.field-meta.xml
<CustomField>
    <fullName>Move__c</fullName>
    <formula>TM__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Move</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Move__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Moves</relationshipLabel>
    <relationshipName>Moves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <displayFormat>PKMN-{0000}</displayFormat>
        <label>Pokemon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Current_HP__c.field-meta.xml
<CustomField>
    <fullName>Current_HP__c</fullName>
    <label>Current HP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/In_Party__c.field-meta.xml
<CustomField>
    <fullName>In_Party__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Party?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Max_HP__c.field-meta.xml
<CustomField>
    <fullName>Max_HP__c</fullName>
    <label>Max HP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pokemon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Pokemon_Name__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_Name__c</fullName>
    <formula>Pokedex_Entry__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pokemon Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Modifiers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status_Modifiers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Paralyzed</fullName>
    </customValue>
    <customValue>
        <fullName>Burn</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Confused</fullName>
    </customValue>
    <masterLabel>Status Modifiers</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Controllers/pkmnCenterController.cls
public class pkmnCenterController {
    
    @AuraEnabled
    public static list<Pokemon__c> getPartyPkmn(string UserId){
        
        list<Pokemon__c> partyPkmn = new list<Pokemon__c>([
            SELECT Id, Pokemon_Name__c, Current_HP__c, Max_HP__c, Status__c
            FROM Pokemon__c 
            WHERE Owner__c = :UserId
            AND In_Party__c = true
            LIMIT 6]);
        
        system.debug('Party Pokemon:');
        for(Pokemon__c pkmn : partyPkmn){
            System.debug(pkmn.Pokemon_Name__c);
        }

        return partyPkmn;
    }

    @AuraEnabled
    public static void healPartyPkmn(list<Pokemon__c> partyPkmn){

        for(Pokemon__c pkmn : partyPkmn){
            pkmn.Current_HP__c = pkmn.Max_HP__c;
            pkmn.Status__c = null;
        }

        update partyPkmn;

        List<Move__c> pkmnMoves = new List<Move__c>([
            SELECT Id, PP__c, Max_PP__c 
            FROM Move__c
            WHERE Pokemon__c IN :partyPkmn
            ]);
        
        List<Move__c> movesToUpdate = new List<Move__c>();
        for(Move__c move : pkmnMoves){
            if(move.PP__c != move.Max_PP__c && move.Max_PP__c != null){
                move.PP__c = move.Max_PP__c;
                movesToUpdate.add(move);
            }
        }

        if(!movesToUpdate.isEmpty()){
            update movesToUpdate;
        }


    }
    
}